### ISSUE TITLE
Suppressing Rules

### ISSUE THREAD

**Issue by patsimon** [rcw3bb/gs-codenarc-ext#2]
Thanks for writing the extension - very handy.

I have just played around with rule suppression using all the techniques documented at https://codenarc.org/codenarc-configuring-rules.html

(eg. @SuppressWarnings('GosuReturnCount') or using // codenarc-disable doesn't appear have any affect)

From my experience, none of these appear to supress the rules.

Before I experiment any further, can I check that this is indeed the case?

Regards,

Patrick

**Comment by rcw3bb** [comment]
Hi @patsimon, try version 1.1.0 for the Support for **Disabling Rules From Comments**

**Comment by lskeet** [comment]
Hi @rcw3bb , while **Disabling Rules From Comments** is now working, **Disabling Rules Using @SuppressWarnings** still appears to not work.
Is it possibly this extension isn't subclassing `AbstractAstVisitorRule` as noted in the CodeNarc [documentation](https://codenarc.org/codenarc-configuring-rules.html)?
