### ISSUE TITLE
Line Numbers on Rule Violations are wrong

### ISSUE THREAD

**Issue by patsimon** [rcw3bb/gs-codenarc-ext#3]
HI there,

I just upgraded to version 1.1.0

I have run codenarc against my codebase and the line numbers that show in the report against any given violation that relate to a function declaration appear to be incorrect

I have noticed this for GosuCyclomaticComplexity and GosuFunctionSize

**Comment by rcw3bb** [comment]
Version 1.1.1 should fix this.
